version: '3'

services:
  client:
    build:
      context: ./client/ 
      dockerfile: Dockerfile
    restart: always
    stdin_open: true
    ports:
      - "3500:3000" 
    depends_on: 
      - server 
    environment: 
      SERVER_URL: "172.19.0.1:8080"
    volumes:
      - "./client/src:/app/src"
    networks:
      - backend
    command: ["/usr/local/bin/npm", "start"]

  server:
    build:
      context: ./server/ 
      dockerfile: Dockerfile
    ports:
      - "8500:8080" 
    depends_on: 
      - database
    environment: 
      DATABASE_URL: "172.19.0.1:27018"
    networks: 
      - backend
    command: ["./main"]

  database:
    image: "mongo:latest"
    ports:
      - "27018:27017"
    restart: unless-stopped
    volumes:
      - "./database/data:/data/db"
    logging:
      driver: "none"
    networks: 
      - backend

networks:
  backend: 