- hosts: localhost

  tasks:
  - name: Start the Backend Database
    docker_container:
      name: bitboardDatabase
      image: mongo:latest
      ports:
        - "27018:27017"
      volumes:
        - ./data:/data/db
    become: yes

  - name: Compile Go Server
    shell: go build main.go
      
  - name: Startup go server
    shell: ./main

  - name: Startup frontend
    shell: npm start